language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  #- 5.2
  # aliased to a recent 5.3.x version
  #- 5.3
  # aliased to a recent 5.4.x version
  - 5.4

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#  - DB=pgsql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -u root -h 127.0.0.1 < "sql schema/dump.sql"

# omitting "script:" will default to phpunit
script: phpunit --configuration application/tests/phpunit.xml